### ISSUE TITLE
Publish initial release to npm

### ISSUE THREAD

**Issue by thisisdano** [uswds/uswds-gulp#1]
If we want folks to try out this gulp package, we should ask them to use `npm` for downloads instead of directly from github.

**Comment by kdimatteo** [comment]
I was also thinking this as I read the README. Is there a namespace this should be published under?

**Comment by thisisdano** [comment]
We'll be doing this, but via https://github.com/uswds/uswds-compile/pull/1 in [uswds-compile](https://github.com/uswds/uswds-compile). When complete and merged, we'll publish to `@uswds/compile`.
