### ISSUE TITLE
Reinstate `gulp-notify`

### ISSUE THREAD

**Issue by thisisdano** [uswds/uswds-gulp#10]
As we saw in #8, using `gulp-notify` was causing a syntax error:

```
[12:11:35] gulp-notify: [Error in notifier] SyntaxError in plugin "gulp-notify"
Message:
    Unexpected token { in JSON at position 129
```

This appears to be an upstream error, captured in mikaelbr/gulp-notify#129
When this upstream error is resolved, we should reinstate `gulp-notify` so everyone can enjoy hearing that satisfying "pop" sound again.

**Comment by mejiaj** [comment]
The last release for `gulp-notify` was in [Jan 2018](https://github.com/mikaelbr/gulp-notify/releases). 

Maybe we should consider [node-notifier](https://www.npmjs.com/package/node-notifier), which looks to be under active development.

**Comment by thisisdano** [comment]
Closed as stale
