### ISSUE TITLE
`css-mqpacker` has been deprecated

### ISSUE THREAD

**Issue by thisisdano** [uswds/uswds-gulp#11]
The postcss plugin we use for collecting similar media queries, `css-mqpacker` is no longer maintained. See https://github.com/hail2u/node-css-mqpacker

This plugin works well and I don't think it's a concern to have this deprecated package in our toolchain — at least in the short term. But we will want to research possible replacements and move in the direction of replacing this deprecated package.

We could consider https://www.npmjs.com/package/gulp-group-css-media-queries though we couldn't include it as a postcss plugin and it would likely break our sourcemaps.

**Comment by mejiaj** [comment]
`gulp-group-css-media-queries` is not actively maintained, unfortunately.

Here are some I've looked at:
New (left) / Old (right)

- [postcss-sort-media-queries](https://github.com/solversgroup/postcss-sort-media-queries)
![image](https://user-images.githubusercontent.com/3385219/73094214-bd9e1000-3ea5-11ea-8179-02c7a97c30b4.png)

- [postcss-combine-media-query](https://github.com/SassNinja/postcss-combine-media-query)
Doesn't sort media queries.
![image](https://user-images.githubusercontent.com/3385219/73093268-c261c480-3ea3-11ea-97da-8659af74a742.png)


## Outdated
- [gulp-group-css-media-queries](https://github.com/avaly/gulp-group-css-media-queries#readme)
- [gulp-clean-css](https://github.com/scniro/gulp-clean-css) up-to-date, but based on clean-css which [isn't maintained anymore](https://github.com/jakubpawlowicz/clean-css/issues/1105).

**Comment by thisisdano** [comment]
We no longer have a media-query packing requirement as of USWDS 2.5.0
