### ISSUE TITLE
uswds-gulp - Not found in npm registry

### ISSUE THREAD

**Issue by jeremyzilar** [uswds/uswds-gulp#15]
Recently, I have been getting this error when I go to update the NPM packages (`npm update`) on my project.

```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/uswds-gulp - Not found
npm ERR! 404 
npm ERR! 404  'uswds-gulp@^0.0.2' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jeremy/.npm/_logs/2020-03-07T18_45_55_130Z-debug.log
```

Which I find a bit odd, since I swear it was working before. 
And in my `packages.json`, I see that I have it set up as
```
"uswds": "^2.4.0",
"uswds-gulp": "^0.0.2"
```

Did something change, or did I never set it up correctly the first time and somehow never encountered this?

**Comment by jeremyzilar** [comment]
Running the install scripts found in the README fixes this https://github.com/uswds/uswds-gulp#installation

**Comment by mejiaj** [comment]
Closing this issue, see README for solution.
