### ISSUE TITLE
postcss-csso required for gulp setup

### ISSUE THREAD

**Issue by amcdevitt97** [uswds/uswds-gulp#17]
Just tried setting up USWDS gulp and it told me that postcss-csso wasn't installed. It's a package not mentioned in the required packages list. After installing it I was able to run gulp init with no problems. Making this issue so that contributors might be able to update the list and other people who have issues with the setup might be able to debug it using this issue.

![Screen Shot 2020-06-09 at 4 27 45 PM](https://user-images.githubusercontent.com/12824100/84196822-cbc48580-aa6e-11ea-921a-d53d11cdae73.png)

**Comment by mejiaj** [comment]
@amcdevitt97 thanks for pointing this out! We'll look into what exactly we need and if that matches up with the docs.
