### ISSUE TITLE
Apparent syntax error in npm install command from README

### ISSUE THREAD

**Issue by vz3** [uswds/uswds-gulp#19]
Per README, attempted to run:
`npm install autoprefixer gulp@^4.0.2 gulp-replace sass gulp-sass gulp-sourcemaps gulp-postcss postcss-csso uswds@latest uswds-gulp@github:uswds/uswds-gulp --save-dev`

Received error `zsh: no matches found: gulp@^4.0.2`

I attempted again removing the caret and it appeared to run successfully.

**Comment by thisisdano** [comment]
Huh! I can't replicate the error locally — and I don't _think_ it's related to the package syntax in `npm` but I'll remove the caret. I wonder if it's something in your zsh setup where the caret is assigned some special functionality?

**Comment by thisisdano** [comment]
Also hi vz!

**Comment by mejiaj** [comment]
Yes, it seems to be a ZSH thing. I've noticed it with other NPM commands as well (like setting a specific git branch).

Putting it in works (if you're using ZSH)`"gulp@^4.0.2"`.

**Comment by thisisdano** [comment]
Fixed in https://github.com/uswds/uswds-gulp/pull/20
