### ISSUE TITLE
Init script doesn't copy .browserslistrc

### ISSUE THREAD

**Issue by thisisdano** [uswds/uswds-gulp#22]
Autoprefixer needs the `.browserslistrc` file to work properly, but the init files doesn't copy it and documentation doesn't mention it

**Comment by mejiaj** [comment]
@thisisdano should we add it to README that users should copy it if they don't already have it?

```bash
cp node_modules/uswds-gulp/.browserslistrc .
```

Otherwise we'd probably have to check to see if the file already exists in their project and copy it if it doesn't.

**Comment by thisisdano** [comment]
Let's add it to the README, as you suggest, just as we do with the gulpfile.
