### ISSUE TITLE
Possible bugs with the USWDS Gulp setup

### ISSUE THREAD

**Issue by jeremyzilar** [uswds/uswds-gulp#3]
Here are the few modifications I needed to make to the GULP set up to get this to work.

**1. Sourcemaps were not creating a new file** 
So I swapped the order of these two lines, so that `sourcemaps.write` came first. 
```
.pipe(sourcemaps.write('.'))
.pipe(gulp.dest(`${CSS_DEST}`))
```
Not sure why this works, and the other configuration doesn't.

**2. style.css is not being overwritten** 
Maybe there is a larger issue going on here, but I am not able to get GULP to overwrite my `/assets/css/styles.css` file
via `.pipe(gulp.dest(`${CSS_DEST}`))`. However, when I delete the `/assets/css/styles.css` file, and re-run gulp, it works.

Steps to repeat the bug:
1. Check out this branch: https://github.com/GSA/digitalgov-workflow/tree/uswds-2.0
2. Run Jekyll
2. Run `gulp watch`
3. Change a USWDS setting (e.g. typeface)
4. Save
4. Check that gulp is running
4. Refresh localhost
(nothing changes)

Now delete the `/assets/css/styles.css` file and try re-saving a USWDS setting.
It builds the file and the settings have been applied.

**Comment by kognise** [comment]
I can't seem to reproduce the second issue, it's been working fine for me.

**Comment by thisisdano** [comment]
First issue was fixed here I think: https://github.com/uswds/uswds-gulp/pull/4

**Comment by thisisdano** [comment]
Closing stale issue
