### ISSUE TITLE
Updating suggestions

### ISSUE THREAD

**Issue by smustgrave** [uswds/uswds-gulp#34]
This is more a question.  After you run gulp init and get everything you need.  And start making changes.  If a new version comes out how do you best get those changes without losing previous changes?

**Comment by smustgrave** [comment]
Some more detail.

We ran git init almost a year ago. Got our scss, imgs, etc. We have added custom changes obviously since then but now that 2.11 is out I'm curious how others update. If we run the copy scss task then our custom work is gone. So not sure what the proper workflow is.

**Comment by mejiaj** [comment]
Thanks for your question @smustgrave! This would be a good candidate for providing guidance. We're working on addressing this in the near future.

**Comment by mejiaj** [comment]
Responded via ZenDesk. 

Closing this in favor of issue https://github.com/uswds/uswds/issues/4152
