### ISSUE TITLE
Please update dependencies

### ISSUE THREAD

**Issue by danizen** [uswds/uswds-gulp#42]
I cannot follow the instructions on using uswds-gulp without first updating uswds-gulp.   Please update:

```
(nlmcatutils) NLM01991848OCCS:code davisda4$ cd uswds-gulp
(nlmcatutils) NLM01991848OCCS:uswds-gulp davisda4$ npm install
npm WARN ancient lockfile 
npm WARN ancient lockfile The package-lock.json file was created with an old version of npm,
npm WARN ancient lockfile so supplemental metadata must be fetched from the registry.
npm WARN ancient lockfile 
npm WARN ancient lockfile This is a one-time fix-up, please be patient...
npm WARN ancient lockfile 
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated phantomjs-prebuilt@2.1.16: this package is now deprecated
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.

added 723 packages, and audited 724 packages in 29s

55 packages are looking for funding
  run `npm fund` for details

15 vulnerabilities (4 low, 5 moderate, 6 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details
```

**Comment by mejiaj** [comment]
How long ago did you install USWDS-Gulp? Can you share your `package.json` file?

**Comment by smustgrave** [comment]
+1 for this.  Know there is a gulp 5.x branch available for one

{
  "name": "PRAC",
  "version": "2.0.0",
  "description": "PRAC Drupal Theme",
  "private": true,
  "scripts": {
    "init": "npm i --legacy-peer-dep; gulp",
    "build": "gulp",
    "lint": "gulp scss-lint; gulp js-lint",
    "styleguide": "gulp styleguide",
    "imagemin": "gulp imagemin",
    "watch": "gulp watch",
    "scss": "gulp scss"
  },
  "paths": {
    "dist": {
      "css": "./css/",
      "js": "./js/",
      "sg": "./styleguide/",
      "img": "./images/"
    },
    "scss": [
      "./components/**/*.scss"
    ],
    "css": [
      "./*.css"
    ],
    "js": [
      "./components/**/*.js"
    ],
    "templates": [
      "./templates/**/*.twig",
      "./styleguide/*.html"
    ]
  },
  "vars": {
    "cssName": "style.css",
    "cssMinName": "style.min.css",
    "jsName": "main.js",
    "sgName": "index.html"
  },
  "devDependencies": {
    "autoprefixer": "^10.2.5",
    "cssnano": "^5.0.0",
    "del": "^6.0.0",
    "fs": "0.0.1-security",
    "gulp": "^4.0.2",
    "gulp-cached": "^1.1.1",
    "gulp-clean-css": "^4.3.0",
    "gulp-concat": "^2.6.1",
    "gulp-eslint": "^6.0.0",
    "gulp-imagemin": "^4.1.0",
    "gulp-load-plugins": "^2.0.3",
    "gulp-newer": "^1.4.0",
    "gulp-pipe": "^1.0.4",
    "gulp-plumber": "^1.2.1",
    "gulp-postcss": "^9.0.0",
    "gulp-rename": "^2.0.0",
    "gulp-replace": "^1.0.0",
    "gulp-sass": "^4.1.0",
    "gulp-sass-glob": "^1.1.0",
    "gulp-sass-lint": "^1.4.0",
    "gulp-shell": "^0.8.0",
    "gulp-sourcemaps": "^3.0.0",
    "gulp-svg-sprite": "^1.5.0",
    "gulp-uglify": "^3.0.2",
    "gulp-uglify-es": "^2.0.0",
    "js-yaml": "^4.0.0",
    "kss": "^3.0.0",
    "michelangelo": "^0.8.0",
    "postcss": "^8.2.10",
    "postcss-csso": "^5.0.1",
    "uswds": "^2.12.0",
    "uswds-gulp": "github:uswds/uswds-gulp"
  },
  "dependencies": {
    "npm": "^7.24.2",
    "require-dir": "^1.2.0"
  },
  "babel": {
    "presets": [
      [
        "@babel/preset-env",
        {
          "targets": {
            "browsers": [
              "IE 11, last 2 versions"
            ]
          },
          "useBuiltIns": "entry"
        }
      ]
    ],
    "plugins": [
      [
        "@babel/plugin-transform-runtime",
        {
          "regenerator": true
        }
      ]
    ]
  }
}

**Comment by danizen** [comment]
22 days ago, as an evaluation of how to get our branch's web applications to USWDS. The NLM OCCS/AB branch has an assets repository which we use for common assets such as jquery. Placing a themed version of USWDS using gulp will be an ideal way to get the entire branch to use the same themed version of USWDS.

Since the first webapp I am trying is already using webpack, I pulled in uswds alone, added the SCSS to the webpack bundle build, and used the FileCopy webpack plugin to copy the javascript since it didn't seem quite as modular.
