### ISSUE TITLE
Repeated Dependencies gulp-sass and sass

### ISSUE THREAD

**Issue by smustgrave** [uswds/uswds-gulp#47]
Error: Could not define the property "sass", you may have repeated dependencies in your package.json like "gulp-sass" and "sass"

Any suggestions for how to resolve this?

**Comment by mejiaj** [comment]
Make sure you're using the latest packages and at least v16 of node.

If you get this figured out, please share your solution so we can close this ticket out.

**Comment by smustgrave** [comment]
We got around this with a different set of packages I think.  But haven't looked at it in a while.  We switched over to uswds-compile on my current project.  So if uswds-gulp is essentially deprecated I say close it.

**Comment by mejiaj** [comment]
Sounds good. Will close, thanks!
